pipeline:
  identifier: Build_ashapiro9912345_harness_u_1765723316223
  name: Build harness-u
  orgIdentifier: default
  projectIdentifier: Testwithai
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1765722537731
        repoName: ashapiro9912345/harness-u
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
